serviceTree:
  landscape: suicune
  cluster: opal-ruby

otelAddress: ""

projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster
  sulfone:
    desc: CyanPrint - Next-generation scaffolding engine
  nitroso:
    desc: BunnyBooker - Bunnies to help you book KTM tickets

url: https://deploy.atomi.cloud

rbac:
  enable: true
  group: https://atomi.cloud/roles
  name: Atomi
  issuer: https://atomicloud-internal.jp.auth0.com/
  clientID: F27LbZI3AsD4mQCM3wWTkBquVGlqCRDr # infisical-scan:ignore
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

github:
  secretName: argo-cd-creds
  url: "https://github.com/AtomiCloud"
  type: "helm"
  internal:
    enable: false
  external:
    enable: true
    refreshInterval: 1h
    usernameRef: "MANUAL_GITHUB_USERNAME"
    passwordRef: "MANUAL_GITHUB_PASSWORD"

sso:
  internal:
    enable: false
  external:
    enable: true
    remoteSecretName: "MANUAL_AUTH0_CLIENT_SECRET"

radon:
  enable: true
  appName: radon
  releaseName: radon
  repoURL: https://github.com/AtomiCloud/sulfoxide.radon
  targetRevision: HEAD
  path: chart
  values: [ "values.yaml", "values.entei.opal-ruby.yaml" ]

connector:
  clusters:
    entei:
      ruby:
        refreshInterval: 1h
        remoteSecretName: ENTEI_RUBY_KUBECONFIG
        destination: "https://8f57e499-104a-437a-a4cd-04be277aa46c.k8s.ondigitalocean.com"
        deployAppSet: false
        aoa:
          enable: false
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-ruby-carbon
          values: [ "values.yaml", "values.entei.ruby.yaml" ]
      opal:
        refreshInterval: 1h
        remoteSecretName: ENTEI_OPAL_KUBECONFIG
        destination: "https://6d009d8e-655d-4536-aa0a-b5abd515b1ea.k8s.ondigitalocean.com"
        deployAppSet: false
        aoa:
          enable: false
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-opal-carbon
          values: [ "values.yaml", "values.entei.opal.yaml" ]
      onyx:
        refreshInterval: 1h
        remoteSecretName: ENTEI_ONYX_KUBECONFIG
        destination: "https://CA529DC636C1CB84B2A643034051AE1F.gr7.ap-southeast-1.eks.amazonaws.com"
        deployAppSet: false
        aoa:
          enable: false
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-onyx-carbon
          values: [ "values.yaml", "values.entei.onyx.yaml" ]
