serviceTree:
  landscape: suicune
  cluster: opal-ruby

otelAddress: ""

projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster

url: https://deploy.atomi.cloud

rbac:
  enable: true
  group: https://atomi.cloud/roles
  name: Atomi
  issuer: https://atomicloud-internal.jp.auth0.com/
  clientID: F27LbZI3AsD4mQCM3wWTkBquVGlqCRDr # infisical-scan:ignore
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

github:
  secretName: argo-cd-creds
  url: "https://github.com/AtomiCloud"
  type: "helm"
  internal:
    enable: false
  external:
    enable: true
    refreshInterval: 1h
    usernameRef: "GITHUB_USERNAME"
    passwordRef: "GITHUB_PASSWORD"

sso:
  internal:
    enable: false
  external:
    enable: true
    remoteSecretName: /suicune/manual/argocd/auth0-client-secret

#  clusters:
#    pichu:
#      opal:
#        # -- refresh interval for fetching the secret from remote
#        refreshInterval: 24h
#        # -- secret for the cluster
#        remoteSecretName: /suicune/auto/argocd/cluster-connector-pichu-opal
#        # -- enable App of Apps
#        aoa:
#          enable: true
#          repo: https://github.com/AtomiCloud/helm.systems_app-of-apps
#          version: HEAD
#          path: chart
#          release: pichu-opal-bootstrap
#          values: [ "values.pichu.opal.yaml" ]
