serviceTree:
  landscape: suicune
  cluster: opal-ruby

otelAddress: ""

projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster

url: https://deploy.atomi.cloud

rbac:
  enable: true
  group: https://atomi.cloud/roles
  name: Atomi
  issuer: https://atomicloud-internal.jp.auth0.com/
  clientID: F27LbZI3AsD4mQCM3wWTkBquVGlqCRDr # infisical-scan:ignore
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

github:
  secretName: argo-cd-creds
  url: "https://github.com/AtomiCloud"
  type: "helm"
  internal:
    enable: false
  external:
    enable: true
    refreshInterval: 1h
    usernameRef: "MANUAL_GITHUB_USERNAME"
    passwordRef: "MANUAL_GITHUB_PASSWORD"

sso:
  internal:
    enable: false
  external:
    enable: true
    remoteSecretName: "MANUAL_AUTH0_CLIENT_SECRET"

connector:
  clusters:
    entei:
      opal:
        refreshInterval: 1h
        remoteSecretName: ENTEI_OPAL_KUBECONFIG
        aoa:
          enable: true
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-opal-bootstrap
          values: [ "values.yaml", "values.entei.opal.yaml" ]
