serviceTree:
  landscape: suicune
  cluster: opal-ruby

otelAddress: ""

projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster
  sulfone:
    desc: CyanPrint - Next-generation scaffolding engine
  nitroso:
    desc: BunnyBooker - Bunnies to help you book KTM tickets

url: https://deploy.atomi.cloud

rbac:
  enable: true
  group: https://atomi.cloud/roles
  name: Atomi
  issuer: https://atomicloud-internal.jp.auth0.com/
  clientID: F27LbZI3AsD4mQCM3wWTkBquVGlqCRDr # infisical-scan:ignore
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

github:
  secretName: argo-cd-creds
  url: "https://github.com/AtomiCloud"
  type: "helm"
  internal:
    enable: false
  external:
    enable: true
    refreshInterval: 1h
    usernameRef: "MANUAL_GITHUB_USERNAME"
    passwordRef: "MANUAL_GITHUB_PASSWORD"

sso:
  internal:
    enable: false
  external:
    enable: true
    remoteSecretName: "MANUAL_AUTH0_CLIENT_SECRET"

connector:
  clusters:
    entei:
      ruby:
        refreshInterval: 1h
        remoteSecretName: ENTEI_RUBY_KUBECONFIG
        destination: "https://03554f79-3c01-496e-974a-6cf3a793914a.k8s.ondigitalocean.com"
        aoa:
          enable: true
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-ruby-carbon
          values: [ "values.yaml", "values.entei.ruby.yaml" ]
      opal:
        refreshInterval: 1h
        remoteSecretName: ENTEI_OPAL_KUBECONFIG
        destination: "https://a931be28-153b-4a85-b40a-f47cdd828a33.k8s.ondigitalocean.com"
        aoa:
          enable: true
          repo: https://github.com/AtomiCloud/sulfoxide.carbon
          version: HEAD
          path: chart
          release: entei-opal-carbon
          values: [ "values.yaml", "values.entei.opal.yaml" ]
