serviceTree:
  landscape: suicune
  cluster: opal
  platform: systems
  service: deployment-platform
  module: argocd

argo-cd:
  configs:
    cm:
      create: false
    params:
      create: false
  global:
    logging:
      format: json
      level: info
  dex:
    enabled: false



kustomize: true
jsonnet: true
helm: true
admin: true
exec: true
applicationWait: true
#banner: "hello everyone!"

otelAddress: ""

projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster

url: https://deploy.atomi.cloud

rbac:
  enable: true
  group: https://atomi.cloud/roles
  name: Atomi
  issuer: https://atomicloud-internal.jp.auth0.com/
  clientID: ""
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

#
auth:
  secretName: argo-cd-creds
  internal:
    enable: false
    username: ""
    password: ""
    url: ""
    type: ""
  external:
    enable: true
    refreshInterval: 1h
    remoteSecretName: /suicune/github/credentials
    secretStore:
      name: aws-ssm-secret-store
      kind: ClusterSecretStore
    policy:
      creation: Owner
      deletion: Retain
sso:
  secretName: argo-cd-sso-secret
  internal:
    enable: false
    secret: ""
  external:
    enable: true
    refreshInterval: 1h
    remoteSecretName: /suicune/auth0/client_secret
    secretStore:
      name: aws-ssm-secret-store
      kind: ClusterSecretStore
    policy:
      creation: Owner
      deletion: Retain
connector:
  secretStore:
    # -- Name of the Secret Store
    name: awsssm-store
    # -- Kind of the Secret Store: ClusterSecretStore or SecretStore
    kind: ClusterSecretStore
  # -- Secret policy
  policy:
    # -- Creation policy
    creation: Owner
    # -- Deletion policy
    deletion: Retain
  clusters: {}
#    pichu:
#      opal:
#        # -- refresh interval for fetching the secret from remote
#        refreshInterval: 24h
#        # -- secret for the cluster
#        remoteSecretName: /suicune/clusters/pichu-opal
#        # -- enable App of Apps
#        aoa:
#          enable: true
#          repo: https://github.com/AtomiCloud/helm.systems_app-of-apps
#          version: HEAD
#          path: chart
#          release: pichu-opal-bootstrap
#          values: [ "values.pichu.opal.yaml" ]
