# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: sulfoxide
  service: chlorine
  layer:  "1"

# -- ArgoCD Specific configuration. See [ArgoCD Helm Documentation](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd)
argo-cd:
  configs:
    cm:
      create: false
    params:
      create: false
    rbac:
      create: false
  global:
    logging:
      format: json
      level: info
  dex:
    enabled: false

# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/weight: "-5"
  # -- Store name to create
  storeName: doppler
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "SULFOXIDE_HELIUM"

# -- Enable Kustomize Application
kustomize: true
# -- Enable JSONNET Application
jsonnet: true
# -- Enable Helm Application
helm: true
# -- Enable Admin Access
admin: true
# -- Enable Exec in ArgoCD
exec: true
# -- Enable waiting in sync-waves
applicationWait: true
# -- Banner to show in ArgoCD UI
banner: ""

# -- OTEL Collector Endpoint
otelAddress: ""

# -- Projects to create in ArgoCD
projects:
  bootstrap:
    desc: Bootstrap Project used to setup the cluster

# -- URL of ArgoCD endpoint
url: https://deploy.atomi.cloud

# -- RBAC Setup
rbac:
  # -- Enable of RBAC
  enable: true
  # -- Group claim to use for OIDC for RBAC
  group: https://atomi.cloud/roles
  # -- Name of the OIDC Provider
  name: Atomi
  # -- Name of OIDC Issuer
  issuer: https://atomicloud-internal.jp.auth0.com/
  # -- Client ID for OIDC
  clientID: ""
  # -- Scopes to request from OIDC
  requestedScopes:
    - openid
    - profile
    - email
    - https://atomi.cloud/roles

# -- GitHub Auth Setup
github:
  # -- Secret name of Github Auth
  secretName: argo-cd-creds
  # -- ArgoCD Credential Type
  url: ""
  # -- ArgoCD Credential Type
  type: ""
  # -- Internal Secret, Hard coded secrets
  internal:
    # -- Enable Internal Secret
    enable: false
    # -- Username for Github Auth
    username: ""
    # -- Password for Github Auth
    password: ""
  # -- External Secrets
  external:
    # -- Enable External Secrets
    enable: true
    # -- Refresh Interval for fetching the secret from remote
    refreshInterval: 1h
    # -- Username Remote Reference
    usernameRef: ""
    # -- Password Remote Reference
    passwordRef: ""
    secretStore:
      # -- Name of the Secret Store
      name: doppler
      # -- Kind of the Secret Store: `ClusterSecretStore` or `SecretStore`
      kind: SecretStore
    # -- External Secret Policy
    policy:
      # -- Creation Policy
      creation: Owner
      # -- Deletion Policy
      deletion: Retain

# -- SSO Secret using OIDC
sso:
  # -- Secret Name of SSO Secret
  secretName: argo-cd-sso-secret
  # -- Internal Secret, Hard coded secrets
  internal:
    # -- Enable Internal Secret
    enable: false
    # -- Secret for SSO
    secret: ""
  # -- External Secret Configuration
  external:
    # -- Enable External Secret
    enable: true
    # -- Refresh Interval for fetching the secret from remote
    refreshInterval: 1h
    # -- Secret Remote Reference for OIDC Client Secret
    remoteSecretName: ""
    secretStore:
      # -- Name of the Secret Store
      name: doppler
      # -- Kind of the Secret Store: `ClusterSecretStore` or `SecretStore`
      kind: ClusterStore
    # -- External Secret Policy
    policy:
      # -- Creation policy
      creation: Owner
      # -- Deletion policy
      deletion: Retain

# -- ApplicationSets for L2 Applications
radon:
  # -- Enable ApplicationSets for L2 Applications
  enable: true
  # -- App name of the App of ApplicationSets
  appName: radon
  # -- Release name for Radon
  releaseName: radon
  # -- Radon helm chart repository
  repoURL: https://github.com/AtomiCloud/sulfoxide.radon
  # -- Version for Radon to deploy
  targetRevision: HEAD
  # -- Path in the repository that poitns to the helm chart
  path: chart
  # -- values to use for the helm chart
  values: [ "values.yaml", "values.entei.opal-ruby.yaml" ]

# -- Connectors to other cluster
connector:
  secretStore:
    # -- Name of the Secret Store
    name: doppler
    # -- Kind of the Secret Store: `ClusterSecretStore` or `SecretStore`
    kind: SecretStore
  # -- External Secret Policy
  policy:
    # -- Creation policy
    creation: Owner
    # -- Deletion policy
    deletion: Retain
  # -- Clusters to connect to
  clusters: {}
#    pichu:
#      opal:
#        # -- refresh interval for fetching the secret from remote
#        refreshInterval: 24h
#        # -- secret for the cluster
#        remoteSecretName: /suicune/clusters/pichu-opal
#        # -- enable App of Apps
#        aoa:
#          enable: true
#          repo: https://github.com/AtomiCloud/helm.systems_app-of-apps
#          version: HEAD
#          path: chart
#          release: pichu-opal-bootstrap
#          values: [ "values.pichu.opal.yaml" ]
