version: '3'

env:
  RELEASE_NAME: sulfoxide-helium

includes:
  util: tasks/Taskfile.util.yaml
  kubectl: tasks/Taskfile.kubectl.yaml
  suicune:opal-ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: suicune
      CLUSTER: opal-ruby
  suicune:mica-talc:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: suicune
      CLUSTER: mica-talc

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of ArgoCD
    cmds:
      - task: util:latest
        vars:
          REPO_NAME: argo-cd
          REPO_URL: https://argoproj.github.io/argo-helm
          CHART_NAME: argo-cd
      - >-
        echo "sulfoxide-bromine: $(skopeo list-tags docker://ghcr.io/atomicloud/sulfoxide.bromine/sulfoxide-bromine | jq -r '.Tags[]' | sort -V | tail -n 1)"
