apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:

  url: {{ .Values.url }}
  kustomize.enabled: "true"
  jsonnet.enabled: "true"
  helm.enabled: "true"

  application.resourceTrackingMethod: annotation

  oidc.config: |
    name: {{ .Values.rbac.name }}
    issuer: "{{ .Values.rbac.issuer }}"
    clientID:  {{ .Values.rbac.clientID }}
    clientSecret: ${{ .Values.sso.secretName }}:oidc.auth0.clientSecret
    requestedScopes:
      {{- toYaml .Values.rbac.requestedScopes | nindent 6}}

  helm.valuesFileSchemes: https
  admin.enabled: "{{ .Values.admin }}"

  {{- if .Values.banner }}
  ui.bannercontent: {{ .Values.banner }}
  {{- end }}
  cluster.inClusterEnabled: "true"

  exec.enabled: "{{ .Values.exec }}"

  resource.exclusions: |
    - apiGroups:
        - kyverno.io
      kinds:
        - AdmissionReport
        - BackgroundScanReport
        - ClusterAdmissionReport
        - ClusterBackgroundScanReport
      clusters:
        - '*'
  {{- if .Values.applicationWait }}
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs
{{- end }}
  # helm parity
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.rbac.log.enforce.enable: 'false'
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
