apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  {{- if .Values.otelAddress }}
  otlp.address: {{ .Values.otelAddress }}
  {{- end }}

  controller.resource.health.persist: "true"

  server.insecure: "true"
  server.dex.server.plaintext: "true"
  server.dex.server.strict.tls: "false"
  dexserver.disable.tls: "true"

  controller.log.format: json
  controller.log.level: debug
  controller.operation.processors: '10'
  controller.repo.server.timeout.seconds: '60'
  controller.self.heal.timeout.seconds: '5'
  controller.status.processors: '20'

  server.log.format: json
  server.log.level: debug
  server.repo.server.strict.tls: 'false'
  server.rootpath: ''
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
  server.disable.auth: 'false'
  server.enable.gzip: 'false'
  reposerver.log.format: json
  reposerver.log.level: debug
  reposerver.parallelism.limit: '0'
