{{- if .Values.github.external.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name -}}-external-secret
  annotations:
   {{- include "sulfoxide-helium.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "sulfoxide-helium.labels" . | nindent 4 }}
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: {{ .Values.github.external.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.github.external.secretStore.name }}
    kind: {{ .Values.github.external.secretStore.kind }}
  target:
    name: {{ .Values.github.secretName }}
    creationPolicy: {{ .Values.github.external.policy.creation }}
    deletionPolicy: {{ .Values.github.external.policy.deletion }}
    template:
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
        url: {{ .Values.github.url }}
        type: {{ .Values.github.type }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.github.external.passwordRef }}
    - secretKey: username
      remoteRef:
        key: {{ .Values.github.external.usernameRef }}
{{- end }}
---
{{- if .Values.github.internal.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.secretName }}
  annotations:
     {{- include "sulfoxide-helium.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  labels:
    {{- include "sulfoxide-helium.labels" . | nindent 4 }}
data:
  username: {{ b64enc .Values.github.internal.username }}
  password: {{ b64enc .Values.github.internal.password }}
  url: {{ b64enc .Values.github.url }}
  type: {{ b64enc .Values.github.type }}
{{- end }}
