{{- if .Values.sso.internal.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sso.secretName }}
  annotations:
     {{- include "atomi-deployment-platform.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/part-of: argocd
    {{- include "atomi-deployment-platform.labels" . | nindent 4 }}
data:
  oidc.auth0.clientSecret: {{ b64enc .Values.sso.internal.secret }}
{{- end }}
---
{{- if .Values.sso.external.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.sso.secretName }}
  annotations:
   {{- include "atomi-deployment-platform.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/part-of: argocd
    {{- include "atomi-deployment-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.sso.external.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.sso.external.secretStore.name }}
    kind: {{ .Values.sso.external.secretStore.kind }}
  target:
    name: {{ .Values.sso.secretName }}
    creationPolicy: {{ .Values.sso.external.policy.creation }}
    deletionPolicy: {{ .Values.sso.external.policy.deletion }}
  data:
    - secretKey: oidc.auth0.clientSecret
      remoteRef:
        key: {{ .Values.sso.external.remoteSecretName }}
{{- end }}