{{ range $lk, $lv := .Values.connector.clusters }}
{{ range $ck, $cv := $lv }}
{{ if $cv.enable}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $lk }}-{{ $ck }}-external-secret
  annotations:
    {{- include "sulfoxide-helium.annotations" $ | nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "sulfoxide-helium.labels" $ | nindent 4 }}
    argocd.argoproj.io/secret-type: cluster
spec:
  refreshInterval: {{ $cv.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.connector.secretStore.name }}
    kind: {{ $.Values.connector.secretStore.kind }}
  target:
    name: {{ $lk }}-{{ $ck }}-cluster-secret
    creationPolicy: {{ $.Values.connector.policy.creation }}
    deletionPolicy: {{ $.Values.connector.policy.deletion }}
    template:
      metadata:
        labels: {{- include "sulfoxide-helium.labels" $ | nindent 10 }}
          argocd.argoproj.io/secret-type: cluster
          atomi.cloud/cluster-type: physical
        annotations: {{- include "sulfoxide-helium.annotations" $ | nindent 10 }}
          argocd.argoproj.io/secret-type: cluster
          atomi.cloud/cluster-type: physical
      data:
        name: '{{ `{{ get ( .kubeconfig | fromJson ) "name" }}` }}'
        server: '{{ `{{ get ( .kubeconfig | fromJson ) "server" }}` }}'
        config: '{{ `{{ get ( .kubeconfig | fromJson ) "config" }}` }}'
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: "{{ $cv.remoteSecretName }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $lk }}-{{ $ck }}-external-secret-ca-crt
  annotations:
    {{- include "sulfoxide-helium.annotations" $ | nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "sulfoxide-helium.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $cv.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.connector.secretStore.name }}
    kind: {{ $.Values.connector.secretStore.kind }}
  target:
    name: {{ $lk }}-{{ $ck }}-cluster-secret-ca-crt
    creationPolicy: {{ $.Values.connector.policy.creation }}
    deletionPolicy: {{ $.Values.connector.policy.deletion }}
    template:
      metadata:
        labels: {{- include "sulfoxide-helium.labels" $ | nindent 10 }}
        annotations: {{- include "sulfoxide-helium.annotations" $ | nindent 10 }}
      data:
        ca.crt: '{{ `{{ get (get ((get ( .kubeconfig | fromJson ) "config") | fromJson ) "tlsClientConfig") "caData" | b64dec }}` }}'
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: "{{ $cv.remoteSecretName }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $lk }}-{{ $ck }}-external-secret-bearer-token
  annotations:
    {{- include "sulfoxide-helium.annotations" $ | nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "sulfoxide-helium.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $cv.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.connector.secretStore.name }}
    kind: {{ $.Values.connector.secretStore.kind }}
  target:
    name: {{ $lk }}-{{ $ck }}-cluster-secret-bearer-token
    creationPolicy: {{ $.Values.connector.policy.creation }}
    deletionPolicy: {{ $.Values.connector.policy.deletion }}
    template:
      metadata:
        labels: {{- include "sulfoxide-helium.labels" $ | nindent 10 }}
        annotations: {{- include "sulfoxide-helium.annotations" $ | nindent 10 }}
      data:
        BEARER_TOKEN: '{{ `{{ get ((get ( .kubeconfig | fromJson ) "config") | fromJson ) "bearerToken" }}` }}'
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: "{{ $cv.remoteSecretName }}"
---
{{- end }}
{{- end }}
{{- end }}
